---
vpc2azs:
  template: vpc-2azs.yaml.j2
  Parameters:
    ClassB: 35
vpc2azs2:
  template: vpc-2azs2.yaml.j2
  Parameters:
    ClassB: 33
vpcbasic:
  template: vpc_basic.yaml.j2
s3bucket:
  template: 's3bucket.yaml.j2'
saproxy:
  template: 'ec2_no_asg.yaml.j2'
  Parameters:
    InstanceType: t2.micro
    HostName: saproxy
    IAMRole: jump
    RootDelOnTerm: true
    RootVolSize: 20
  SecurityGroups: ['devvpc2azs-ExternalSecurityGroup']
  Subnet: devvpc2azs-SubnetAPrivate
jumpbox:
  template: 'ec2_basic.yaml.j2'
  Parameters:
    InstanceType: t2.micro
    HostName: jumpbox
    IAMRole: jump
    RootDelOnTerm: true
    RootVolSize: 20
  SecurityGroups: ['devvpc2azs-ExternalSecurityGroup', 'devvpc2azs-SSHSecurityGroup']
  Subnet: devvpc2azs-SubnetAPrivate

box1:
  template: 'ec2_basic.yaml.j2'
  Parameters:
    InstanceType: t2.micro
    HostName: box1
    IAMRole: jump
    RootDelOnTerm: true
    RootVolSize: 20
...
