---
vpc2azs:
  template: vpc-2azs.yaml.j2
  Parameters:
    ClassB: 36
s3bucket:
  template: 's3bucket.yaml.j2'
saproxy:
  template: 'ec2_no_asg.yaml.j2'
  Parameters:
    InstanceType: t2.micro
    HostName: saproxy
    IAMRole: jump
    RootDelOnTerm: true
    RootVolSize: 20
  SecurityGroups: ['devvpc2azs-ExternalSecurityGroup']
  SubnetId: devvpc2azs-SubnetAPrivate
boxa:
  template: 'boxa.yaml.j2'
  Parameters:
    InstanceType: t2.micro
apiecs:
  template: 'ecs_cluster.yaml.j2'
  ecsClusterName: 'api-cluster'
  Parameters:
    InstanceType : 'c4.xlarge'
    HostName : 'apiecs'
    DesiredCapacity : '2'
    MinSize : '1'
    MaxSize : '2'
  VPCZoneIdentifier : [ 'InternalApplicationAZ1a', 'InternalApplicationAZ1b']
  SecurityGroups : [ 'InternalApplicationSG', 'SSH']
...
