---
vpc2azs:
  template: vpc-2azs.yaml.j2
  Parameters:
    ClassB: 36
s3bucket:
  template: 's3bucket.yaml.j2'
saproxy:
  template: 'ec2_no_asg.yaml.j2'
  Parameters:
    InstanceType: t2.micro
    HostName: saproxy
    IAMRole: jump
    RootDelOnTerm: true
    RootVolSize: 20
  SecurityGroups: ['devvpc2azs-ExternalSecurityGroup']
  Subnet: devvpc2azs-SubnetAPrivate
ec2basic:
  template: 'ec2_basic.yaml.j2'
  Parameters:
    InstanceType: t2.micro
    HostName: ec2basic
    IAMRole: jump
    RootDelOnTerm: true
    RootVolSize: 20
  SecurityGroups: ['devvpc2azs-ExternalSecurityGroup']
  Subnet: devvpc2azs-SubnetAPrivate
...
